{% set name = "pymedm" %}
{% set version = "2.2.8" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bad334ac7a7bda7f68adc55713857355331b219fcfb5570e833037d393be4923

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.4.31
    - jaxlib >=0.4.31
    - jaxopt >=0.8.3
    - multiprocess >=0.70.15
    - packaging
    - numpy >=1.26
    - pandas >=2.2
    - scipy >=1.12

test:
  imports:
    - pymedm
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/likeness-pop/
  summary: Penalized Maximum-Entropy Dasymetric Modeling (P-MEDM) in Python
  license: LicenseRef-UT-BATTELLE
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://github.com/likeness-pop/pymedm/

extra:
  recipe-maintainers:
    - jvtcl
    - jGaboardi
